CREATE DATABASE Users
GO
USE Users
GO
CREATE TABLE UsersData(
    Username VARCHAR(100),
	Email VARCHAR(100),
	Password VARCHAR(100),
	IdUserData INT PRIMARY KEY IDENTITY(1,1)
)
GO
CREATE TABLE Posts(
	Title VARCHAR(200),
	Content VARCHAR(MAX),
	CreationDate DATETIME DEFAULT GETDATE(),
	UserId INT,
	Img VARCHAR(MAX),
	IdPost INT PRIMARY KEY IDENTITY(1,1)
)
GO

drop table Posts
